---

- name: Make sure parent directory exists
  file: path={{accumulo_parent_dir}} state=directory owner=root group=root mode=0755 follow=yes

- name: Copy .tgz to {{accumulo_parent_dir}} and unpack it
  unarchive: src=accumulo-{{accumulo_version}}-bin.tar.gz dest={{accumulo_parent_dir}} owner={{accumulo_user}} group={{accumulo_group}} mode=0755 creates="{{accumulo_home}}-{{accumulo_version}}"

- name: Link accumulo version to {{accumulo_home}}
  file: src={{accumulo_home}}-{{accumulo_version}} dest={{accumulo_home}} owner={{accumulo_user}} group={{accumulo_group}} state=link

- name: Create folder {{accumulo_conf_dir | dirname}}
  file: path={{accumulo_conf_dir | dirname}} state=directory owner={{accumulo_user}} group={{accumulo_group}}

- name: Create accumulo link for conf to /etc/accumulo
  file: src={{accumulo_home}}/conf dest={{accumulo_conf_dir}} owner={{accumulo_user}} group={{accumulo_group}} state=link

# Note: Q: Why the '/usr/bin/accumulo' symlink?
# A: 1. why not! 2. it's the same symlink used by the original ansible (so it's easier to overwrite existing one)
- name: Create link for accumulo to /usr/bin
  file: src="{{accumulo_home}}/bin/accumulo" dest=/usr/bin/accumulo owner={{accumulo_user}} group={{accumulo_group}} mode=755 state=link

- name: Build Accumulo native libraries
  command: "{{accumulo_home}}/bin/build_native_library.sh"
  args:
    creates: "{{accumulo_home}}/lib/native/libaccumulo.so"
