---
# need to make sure any existing 'deb' based accumulo is uninstalled
- name: Uninstall Accumulo pkg (if exists)
  apt: pkg=accumulo state=absent

- name: Uninstall old native lib
#  file: path="/usr/lib/accumulo/lib/native/libaccumulo.so" state=absent
  file: path="/usr/lib/accumulo/lib" state=absent

# below tasks should only be done, in case the 'deb' package was removed in this run
- name: Uninstall old logs symlink lib
  file: path="/usr/lib/accumulo/logs" state=absent  recurse=no

- name: Uninstall old accumulo parent dir
  file: path="/usr/lib/accumulo" state=absent  recurse=no

#- name: Uninstall old logs symlink lib
#  file: path="/etc/accumulo/conf" state=absent  recurse=no

# rename the 'conf' dir only if it's a dir not a symlink (like for non-deb installs)
- stat: path=/etc/accumulo/conf
  register: conf_exists
- name: rename (backup) old conf dir (if not a symlink)
  command: "mv /etc/accumulo/conf /etc/accumulo/conf.bak"
  args:
    removes:  "/etc/accumulo/conf"
    creates:  "/etc/accumulo/conf.bak"
  when: conf_exists.stat.isdir is defined and conf_exists.stat.isdir
