---
- name: Configure the PackageCloud APT key
  apt_key: url=https://packagecloud.io/gpg.key state=present

- name: Configure the PackageCloud APT repositories
  apt_repository: repo="deb https://packagecloud.io/azavea/accumulo/ubuntu/ {{ ansible_distribution_release }} main"
                  state=present

- name: Install Accumulo
  apt: pkg=accumulo={{ accumulo_version }} state=present

- name: Build Accumulo native libraries
  command: "/usr/lib/accumulo/bin/build_native_library.sh"
  args:
    creates: "/usr/lib/accumulo/lib/native/libaccumulo.so"

- name: Ensure Accumulo directories are owned by Accumulo user
  file: path={{ item }}
        owner={{ accumulo_user }}
        mode=0755
        state=directory
  with_items:
    - "{{ accumulo_log_dir }}"
    - "{{ accumulo_conf_dir }}"
