---
## Note: With setting the group to hadoop, the deployment script expects the accumulo user having
## full permissions to write on 'hdfs'  (to create a new top-level folder below, during init step)
## Update: Using a workaround now, using a separate task to create the accumulo dir as 'hdfs' user
#
#- name: Add Accumulo user to HDFS supergroup
#  user: name={{ accumulo_user }}
#        append=yes
#        group=hadoop
#        state=present

- name: Configure Accumulo
  template: src={{ item }}.j2
            dest={{ accumulo_conf_dir }}/{{ item }}
            owner={{ accumulo_user }}
            group=root
            mode=0644
  with_items:
    - accumulo-env.sh
    - accumulo-metrics.xml
    - accumulo-site.xml
    - generic_logger.xml
    - log4j.properties
    - monitor_logger.xml

- name: Set master for Accumulo followers
  copy: content="{{ accumulo_leader_host }}"
        dest="{{ accumulo_conf_dir }}/masters"
        mode=0644

## Note: below hdfs cmds only works using 'bash -lc' (only a login shell, reads /etc/profile scripts!)
## Details see: https://github.com/ansible/ansible/issues/4854
- name: Check if accumulo has been initialized
  shell: bash -lc 'hdfs dfs -test -d /accumulo'
  register: hdfs_inited
  ignore_errors: yes

- debug: var=hdfs_inited

## Note: Instead of 'manually' creating this folder, we could also add 'accumulo' to the hadoop 'admins' group
- name: Initialize Accumulo HDFS folder (as hdfs'root user)
  sudo_user: "{{ hdfs_root_user }}"
#  shell: "hdfs dfs -mkdir /accumulo &&  hdfs dfs -chown {{ accumulo_user }}:{{ accumulo_group }} /accumulo"
  shell: bash -lc 'hdfs dfs -mkdir /accumulo &&  hdfs dfs -chown {{ accumulo_user }}:{{ accumulo_group }} /accumulo'
  register: hdfs_dir_created
  when: "hdfs_inited.rc == 1"

- debug: var=hdfs_dir_created.rc

## Also below: if we would use 'bash -lc' we could use the System ENV Vars in accumulo-env.sh
## Anyway: The work of setting usable defaults, was done already
- name: Initialize Accumulo Leader
  sudo_user: "{{ accumulo_user }}"
  command: "accumulo init --instance-name {{ accumulo_instance_name }} --password {{ accumulo_secret }}"
#  when: "hdfs_inited.rc == 1"
  when: hdfs_dir_created is defined and hdfs_dir_created.rc == 0

## Preferred to set state=restarted so that services are restarted for a 'config update' only run
- name: Restart Accumulo Server Master (all services)
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - "accumulo-master"
    - "accumulo-monitor"
    - "accumulo-gc"
    - "accumulo-tracer"
    - "accumulo-tserver"
  when: accumulo_leader == True

- name: Restart Accumulo Follower (tserver only)
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - "accumulo-tserver"
  when: accumulo_leader == False

##Note: was not required to have even the conf/slaves file, see: http://accumulo.apache.org/1.6/accumulo_user_manual.html#_cluster_specification
