---
## Note: With setting the group to hadoop, the deployment script expects the accumulo user having
## full permissions to write on 'hdfs'  (to create a new top-level folder below, during init step)
## Update: Using a workaround now, using a separate task to create the accumulo dir as 'hdfs' user
#
#- name: Add Accumulo user to HDFS supergroup
#  user: name={{ accumulo_user }}
#        append=yes
#        group=hadoop
#        state=present

- name: Configure Accumulo
  template: src={{ item }}.j2
            dest={{ accumulo_conf_dir }}/{{ item }}
            owner={{ accumulo_user }}
            group={{ accumulo_group }}
            mode=0644
  with_items:
    - accumulo-env.sh
    - accumulo-metrics.xml
    - accumulo-site.xml
    - generic_logger.xml
    - log4j.properties
    - monitor_logger.xml

- name: Set master for Accumulo followers
  copy: content="{{ accumulo_leader_host }}"
        dest="{{ accumulo_conf_dir }}/masters"
        mode=0644

- include: config-init.yml
  when: accumulo_initialize


## Preferred to set state=restarted so that services are restarted for a 'config update' only run
- name: Restart Accumulo Server Master (all services)
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - "accumulo-master"
    - "accumulo-monitor"
    - "accumulo-gc"
    - "accumulo-tracer"
    - "accumulo-tserver"
  when: accumulo_leader == True

- name: Restart Accumulo Follower (tserver only)
  service: name={{ item }} enabled=yes state=restarted
  with_items:
    - "accumulo-tserver"
  when: accumulo_leader == False

##Note: was not required to have even the conf/slaves file, see: http://accumulo.apache.org/1.6/accumulo_user_manual.html#_cluster_specification
