---
## Note: below hdfs cmds only works using 'bash -lc' (only a login shell, reads /etc/profile scripts!)
## Details see: https://github.com/ansible/ansible/issues/4854
- name: Check if accumulo has been initialized
  shell: bash -lc 'hdfs dfs -test -d /accumulo'
  register: hdfs_inited
  ignore_errors: yes

- debug: var=hdfs_inited

## Note: Instead of 'manually' creating this folder, we could also add 'accumulo' to the hadoop 'admins' group
- name: Initialize Accumulo HDFS folder (as hdfs'root user)
  sudo_user: "{{ hdfs_root_user }}"
  shell: bash -lc 'hdfs dfs -mkdir /accumulo &&  hdfs dfs -chown {{ accumulo_user }}:{{ accumulo_group }} /accumulo'
  register: hdfs_dir_created
  when: hdfs_inited is defined and hdfs_inited.rc==1

- debug: var=hdfs_dir_created.rc

## Also below: if we would use 'bash -lc' we could use the System ENV Vars in accumulo-env.sh
## Anyway: The work of setting usable defaults, was done already
- name: "Initialize Accumulo Leader (if task hangs, the init cmd is probably waiting for user-input!)"
  sudo_user: "{{ accumulo_user }}"
  command: "accumulo init --instance-name {{ accumulo_instance_name }} --password {{ accumulo_secret }}"
  when: hdfs_dir_created is defined and hdfs_dir_created.rc==0
