---
- name: Configure Accumulo
  template: src={{ item }}.j2
            dest={{ accumulo_conf_dir }}/{{ item }}
            owner={{ accumulo_user }}
            group={{ accumulo_group }}
            mode=0644
  with_items:
    - accumulo-env.sh
    - accumulo-metrics.xml
    - accumulo-site.xml
    - generic_logger.xml
    - log4j.properties
    - monitor_logger.xml
    - auditLog.xml
  notify:
     - Restart Accumulo Master
     - Restart Accumulo Monitor
     - Restart Accumulo Tracer
     - Restart Accumulo Garbage Collector
     - Restart Accumulo Tablet Server

- name: Configure 'masters' config
  copy: content="{{ accumulo_leaders | join('\n') }}"
        dest="{{ accumulo_conf_dir }}/masters"
        owner={{ accumulo_user }}
        group={{ accumulo_group }}
        mode=0644
  notify:
     - Restart Accumulo Master
     - Restart Accumulo Tablet Server

- name: Configure 'slaves' config
  copy: content="{{ accumulo_slaves | join('\n') }}"
        dest="{{ accumulo_conf_dir }}/slaves"
        owner={{ accumulo_user }}
        group={{ accumulo_group }}
        mode=0644
  notify:
     - Restart Accumulo Master
     - Restart Accumulo Tablet Server

- name: Configure 'tracers' config
  copy: content="{{ accumulo_tracers | join('\n') }}"
        dest="{{ accumulo_conf_dir }}/tracers"
        owner="{{ accumulo_user }}"
        group="{{ accumulo_group }}"
        mode=0644
  notify:
     - Restart Accumulo Master
     - Restart Accumulo Tablet Server
