---
- name: Configure Accumulo
  template: src={{ item }}.j2
            dest={{ accumulo_conf_dir }}/{{ item }}
            owner={{ accumulo_user }}
            group={{ accumulo_group }}
            mode=0644
  with_items:
    - accumulo-env.sh
    - accumulo-metrics.xml
    - accumulo-site.xml
    - generic_logger.xml
    - log4j.properties
    - monitor_logger.xml
  notify:
     - Restart Accumulo Master
     - Restart Accumulo Monitor
     - Restart Accumulo Tracer
     - Restart Accumulo Garbage Collector
     - Restart Accumulo Tablet Server

- name: Set master for Accumulo followers
  copy: content="{{ accumulo_leader_host }}"
        dest="{{ accumulo_conf_dir }}/masters"
        mode=0644
