
## AFAIU The idea of the override files is that the services are *not* started automatically
## at the end the ansible deployment.. but only when the cron scheduled scripts below  are run
## Note also: Once any accumulo service was started below, the override file(s) were gone !
- name: Create service definition overrides
  copy: content="manual"
        dest=/etc/init/accumulo-{{ item }}.override
        mode=0644
  with_items:
    - gc
    - master
    - monitor
    - tracer
    - tserver
