---
- name: Create service account for Accumulo
  user: name={{ accumulo_user }}
        system=yes
        home={{ accumulo_user_dir }}
        shell={{ accumulo_user_shell }}
        state=present

- name: Deploy archive to {{accumulo_parent_dir}} and unpack it
  unarchive: src=accumulo-{{accumulo_version}}-bin.tar.gz dest="{{accumulo_parent_dir}}/" owner={{accumulo_user}} group={{accumulo_group}} mode=0755 creates="{{accumulo_parent_dir}}/accumulo-{{accumulo_version}}"

- name: Link accumulo version to {{accumulo_home}}
  file: src={{accumulo_home}}-{{accumulo_version}} state=link dest={{accumulo_home}} owner={{accumulo_user}} group={{accumulo_group}} mode=0755

- name: Create conf parent folder {{accumulo_conf_dir | dirname}}
  file: path={{accumulo_conf_dir | dirname}} state=directory owner={{accumulo_user}} group={{accumulo_group}} mode=0755

- name: Create conf folder link
  file: src={{accumulo_home}}/conf state=link dest={{accumulo_conf_dir}} owner={{accumulo_user}} group={{accumulo_group}} mode=0755

- name: Create log folder {{accumulo_log_dir}}
  file: path={{accumulo_log_dir}} state=directory owner={{accumulo_user}} group={{accumulo_group}} mode=755

- name: Create link for accumulo to /usr/bin
  file: src="{{accumulo_home}}/bin/accumulo" state=link dest=/usr/bin/accumulo owner={{accumulo_user}} group={{accumulo_group}} mode=0755


- include: install-native-lib.yml
