---
- name: Create service account for Accumulo
  user: name={{ accumulo_user }}
        system=yes
        home={{ accumulo_user_dir }}
        shell={{ accumulo_user_shell }}
        state=present

- include: accumulo-1-6.yml
  when: accumulo_version | version_compare('1.6.3', '<') and accumulo_version|version_compare('1.6.0', '>=')

- include: accumulo-distr.yml
  when: accumulo_version | version_compare('1.6.3', '>')
