---
- debug: msg="Accumulo setup started with accumulo_leader={{accumulo_leader}}, accumulo_slave={{accumulo_slave}}"

## before installing from 'binary distribution', call the uninstaller tasks
- include: accumulo-deb-uninstall-with-check.yml
  when: accumulo_uninstall
  tags: uninstall

- include: install.yml
  tags: install

- include: config.yml
  tags: config

- include: initialize.yml
  when: accumulo_initialize and accumulo_leader
  tags: initialize

# Finally once Accumulo was initialized, services can be started (and registered)
- include: service-init.yml
  tags: service-init
