---
- include: install.yml
  tags: install

- include: cron_failover_config_services_overrides.yml
  when: accumulo_cron_failover
  tags: [cron_failover,config]

- include: config.yml
  tags: config


## Initially I added below 2 tasks for the functionality that seemed to be a 'failover' try using cron.
## To use it, uncomment (note: that the task includes existed already, but not below 2 tasks):
- include: cron_failover_accumulo_leader.yml
  when: accumulo_cron_failover and  accumulo_leader == True
  tags: cron_failover

- include: cron_failover_accumulo_follower.yml
  when: accumulo_cron_failover and  accumulo_leader == False
  tags: cron_failover
