---
- debug: msg="started setup of Accumulo v{{accumulo_version}} with accumulo_leader={{accumulo_leader}}, accumulo_slave={{accumulo_slave}}"

- include: install.yml
  tags: install

- include: config.yml
  tags: config

- include: hdfs-folder-init.yml
  when: accumulo_initialize and accumulo_leader
  tags: initialize

- include: service-init.yml
  tags: service-init
