---
- debug: msg="Accumulo setup started with accumulo_leader={{accumulo_leader}}"

- include: install.yml
  tags: install

- include: config.yml
  tags: config

- include: initialize.yml
  when: accumulo_initialize
  tags: initialize

# Finally once Accumulo was initialized, services can be started (and registered)
- include: service-init.yml
  tags: service-init
