---
- name: Configure Accumulo Leader service definitions
  template: src=services/accumulo-upstart-template.conf.j2
            dest=/etc/init/accumulo-{{ item.name }}.conf
            owner=root
            group=root
            mode=0644
  with_items:
    - { name: "gc" }
    - { name: "master" }
    - { name: "monitor" }
  when: accumulo_leader

- name: Configure Accumulo Leader service definitions (Tracer)
  template: src=services/accumulo-upstart-template.conf.j2
            dest=/etc/init/accumulo-{{ item.name }}.conf
            owner=root
            group=root
            mode=0644
  with_items:
    - { name: "tracer" }
  when: inventory_hostname in accumulo_tracers


- name: Configure Accumulo Slave service definitions
  template: src=services/accumulo-upstart-template.conf.j2
            dest=/etc/init/accumulo-{{ item.name }}.conf
            owner=root
            group=root
            mode=0644
  with_items:
    - { name: "tserver" }
  when: accumulo_slave

# Note: No need to set state=started here. the handlers take care (iff configs were created/updated)
- name: Register Accumulo Master services
  service: name={{ item }} enabled=yes
  with_items:
    - "accumulo-master"
    - "accumulo-monitor"
    - "accumulo-gc"
    - "accumulo-tracer"
  when: accumulo_leader

- name: Register Accumulo Tablet-Server (on slaves)
  service: name={{ item }} enabled={{ accumulo_tserver_service_enabled }}
  with_items:
    - "accumulo-tserver"
  when: accumulo_slave
