---
- name: Restart Accumulo Master
  service: name=accumulo-master state=restarted
  when: accumulo_leader and accumulo_service_handlers_enabled

- name: Restart Accumulo Monitor
  service: name=accumulo-monitor state=restarted
  when: accumulo_leader and accumulo_service_handlers_enabled

- name: Restart Accumulo Tracer
  service: name=accumulo-tracer state=restarted
  when: accumulo_leader and accumulo_service_handlers_enabled

- name: Restart Accumulo Garbage Collector
  service: name=accumulo-gc state=restarted
  when: accumulo_leader and accumulo_service_handlers_enabled

- name: Restart Accumulo Tablet Server
  service: name=accumulo-tserver state=restarted
  when: accumulo_slave and accumulo_service_handlers_enabled and accumulo_tserver_service_enabled
