---
- hosts: all

  vars:
    java_version: "7u95-*"

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
#    - { role: "azavea.accumulo" }
    - { role: "lhoss.accumulo" }
